sudo: false
language: php

php:
  - 5.6
  - 7.0

env:
  - MONGO_VERSION=stable

matrix:
  include:
    - php: 7.0
      env: ADAPTER_VERSION="^1.0.0" MONGODB_VERSION=stable

before_script:
  - pecl -q install -f mongodb-${MONGO_VERSION}
  - php --ri mongodb
  - composer self-update
  - composer update --dev --no-interaction --prefer-source

script:
    - ./vendor/bin/phpunit